name: Aurora Latest
on:
  merge_group:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - '**.md'
      - 'system_files/silverblue/**'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'system_files/silverblue/**'
  schedule:
    - cron: '40 6 * * *'  # 6:40 UTC everyday
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      brand_name: aurora
      fedora_version: latest
